[package]
name = "prime_factorization"
version = "0.1.0"
authors = ["Amadeus_vn <git@amas.dev>"]
edition = "2018"

opt-level = 3
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
